find_leads_task:
  description: "Search for businesses in {industry} using online sources and provide their website and contact details."
  expected_output: "A list of 5 companies with their website and contact details."

  
compile_leads_task:
  description: "Format the gathered leads into a structured list."
  expected_output: "A structured lead list formatted as a CSV file."


qualify_leads_task:
  description: >
    Evaluate and rank the collected leads based on relevance to the given industry.
    Consider factors like company size, location, industry keywords, and credibility.
    Remove low-quality leads and only return the top 3 best matches.
  expected_output: >
    A structured list of the 3 most relevant leads with a short justification for why they were chosen.
    Include a score for each lead based on the evaluation criteria.
